### ISSUE TITLE
raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by bastvdn** [thuanz123/enhancing-transformers#4]
Hi, i've got this error when trying to run the simple training, it seems to be linked with visual studio or my environment variables
I'm with anaconda on Windows (had to install the requirements manually)
pytorch==1.12.0
python==3.10.4

Thanks a lot

C:\ProgramData\Anaconda3\envs\enhancing\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Users\BVA\Documents\enhancing-transformers\main.py", line 41, in <module>
    model = initialize_from_config(config.model)
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\utils\general.py", line 40, in initialize_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\modules\stage1\vitvqgan.py", line 36, in __init__
    self.loss = initialize_from_config(loss)
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\utils\general.py", line 40, in initialize_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\utils\general.py", line 36, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\losses\vqperceptual.py", line 14, in <module>
    from .layers import *
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\losses\layers.py", line 19, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\losses\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\BVA\Documents\enhancing-transformers\enhancing\losses\op\fused_act.py", line 11, in <module>
    fused = load(
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\site-packages\torch\utils\cpp_extension.py", line 1524, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\site-packages\torch\utils\cpp_extension.py", line 1963, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\site-packages\torch\utils\cpp_extension.py", line 2090, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ProgramData\Anaconda3\envs\enhancing\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by thuanz123** [comment]
Hi, this issues occurs because you cannot call C++ compiling tools of Window **cl.exe**. You can try to solve it by adding the path to cl.exe in the environment variable PATH. However, unless you are experienced in compiling Pytorch C++ code in Windows, I would advice you to use a Ubuntu machine to setup the project

**Comment by bastvdn** [comment]
Thanks a lot for the answer i'll try tomorrow and close the issue of it works

**Comment by thuanz123** [comment]
Hi @bastvdn , how is it going ? If some issues occur, don't be shy to ask 😄
